language: python

python: '3.6'
sudo: false

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

install:
  - pip install pytest
  - for i in consumers/*/; do pip install -r $i"requirements.txt"; done

script:
  # run tests
  - py.test -vv -r sxX

before_deploy:
  - pip install awscli
  - pip install boto3

notifications:
  email: true
